name: edumentor
description: "edumentor uos app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1  # SVG support for Flutter
  http: ^1.2.2
  mirai_dropdown_menu: ^0.0.9+1
  path_provider: ^2.1.4
  quickalert: ^1.1.0
  rename: ^3.0.2
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  syncfusion_flutter_pdfviewer: ^27.1.56
  uuid: ^4.5.1
  wave_loading_indicator: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/PDFs/
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/icon.png"

